export const DEFAULT_COURSES = {
    "Infantil": ["1º Infantil", "2º Infantil", "3º Infantil"],
    "Primaria": ["1º Primaria", "2º Primaria", "3º Primaria", "4º Primaria", "5º Primaria", "6º Primaria"],
    "ESO": ["1º ESO", "2º ESO", "3º ESO", "4º ESO"]
};

export const schoolData = {
    "Infantil": {
        "1º Infantil": [
            { name: "Adrián H.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Alonso M.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Adrián S.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Fabio F.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Martín M.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" }
        ],
        "2º Infantil": [
            { name: "Andrés V.", info: "Enfermedad: Alergia a mosquitos y arañas. Síntomas: Hinchazón abultada en la zona afectada. Actuación: Aerius, aplicar frío y crema para picaduras. Contacto: Laura (649100661), José (639706440).", severity: "medium" },
            { name: "Helena D", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Fabio I.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Jimena M.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Leyre S.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Lucas H.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Lucía H.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Manuel B.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Mario B.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Mario M.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Mateo M.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Thiago C.", info: "Enfermedad: Diabetes tipo I. Síntomas: Hipoglucemia (Sudores, temblores - leve) o Hipoglucemia con pérdida de conocimiento (Desmayo - grave). Actuación: Si es leve, dar hidratos de carbono. Si es grave, administrar Glucagón.\nContacto: No especificado.", severity: "high" },
            { name: "Valentina R.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Yoel M.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" }
        ],
        "3º Infantil": [
            { name: "Alai F.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Alejandro G.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Alicia G.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Álvaro F.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Aritz F.", info: "Enfermedad: Alergia a las pipas. Síntomas: Erupción, problemas respiratorios. Actuación: Administrar Adrenalina. Contacto: Déborah (635344640).", severity: "high" },
            { name: "Axel F.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Candela B.", info: "Enfermedad: Piel atópica (con brotes). Tratamiento habitual: Corticoides. Contacto: Jose (669610215), Sara (722852911).", severity: "medium" },
            { name: "Daniel A.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Darío I.", info: "Enfermedad: Alergia a proteína de leche, huevo, polen y gramíneas. Síntomas: Urticaria, vómitos. Actuación: Lavar y administrar Zasten 5ml y Estilsona imediatamente. Contacto: Elvira (661211335, 637834692).", severity: "high" },
            { name: "Emma R.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Hernán F.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Izan M.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Mario G.", info: "Enfermedad: Asma. Tratamiento habitual: Desloratadina 5ml, Ventolín, Seretide. Síntomas: Mucha tos. Actuación: Ventolín 100mg (2-3 puff), Seretide 25mg (1-2 puff). Contacto: Jonathan (618940992), María (673724999).", severity: "medium" },
            { name: "Olivia M.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Valeria F.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Valeria G.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Vida R.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" }
        ]
    },
    "Primaria": {
        "1º Primaria": [
            { name: "Adriana B.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "África G.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Aimee C.", info: "Enfermedad: Alergia estacional (polen).\nContacto: No especificado.", severity: "medium" },
            { name: "Alba B.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Alejandro P.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Candela M.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Chloe S.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Guillermo S.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Irene G.", info: "Enfermedad: Asma. Tratamiento: Ventolín (2 puf) solo cuando está muy constipada. Contacto: Esther (659746060).", severity: "medium" },
            { name: "Isabel P.", info: "Enfermedad: Alergia a arañas, mosquitos y lana. Síntomas: Inflamación excesiva y rápida (leve), inflamación extendida (grave). Actuación: Aplicar stick de la mochila (leve), stick+frío y corticoides orales (grave). Contacto: Estela (657826609).", severity: "medium" },
            { name: "Jimena B.", info: "Enfermedad: Asma, alergia al polvo, polen, ácaros. Tratamiento: Seretide (2 puff), Sabultamol (2 puff). Síntomas: Tos crónica. Actuación: Ventolín (2 puf). Contacto: Jessica (633545510).", severity: "medium" },
            { name: "Jorge M.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Lucas B.", info: "Información: Operado de hernia umbilical y fimosis. Indicación: No coger peso.\nContacto: No especificado.", severity: "medium" },
            { name: "Renata G.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Valeria B.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Valeria V.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" }
        ],
        "2º Primaria": [
            { name: "Abril F.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Adrián C.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Alejandro B.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Bruno N.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Daniel G.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Dhulia A.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Emiliana P.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Gisele H.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "India G.", info: "Enfermedad: Leucemia linfoblástica.\nContacto: No especificado.", severity: "high" },
            { name: "Izán G.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Judith B.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Junior T.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Leo F.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Lucas D.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Martina B.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Matías A.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Matías P.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Rodrigo P.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Víctor S.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" }
        ],
        "3º Primaria": [
            { name: "Adriana J.", info: "Enfermedad: Alergia al polen.\nContacto: No especificado.", severity: "medium" },
            { name: "Alba G.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Camila R.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Cayetana B.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Daniel J.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Diana H.", info: "Enfermedad: Pequeño soplo cardíaco, Lipoproteína activa.\nContacto: No especificado.", severity: "high" },
            { name: "Elías R.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Lucía M.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Mahesh V.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "María L.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Martín S.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Orión F.", info: "Enfermedad: Osteocondromatosis múltiple.\nContacto: No especificado.", severity: "medium" },
            { name: "Thiago I.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" }
        ],
         "4º Primaria": [
            { name: "Alondra G.", info: "Enfermedad: Patología crónica bilateral (hipoacusia), alergia al polvo, ácaros, mosquitos, hormigas y al sol.\nContacto: No especificado.", severity: "medium" },
            { name: "Diego G.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Diego M.", info: "Enfermedad: Alergia primaveral.\nContacto: No especificado.", severity: "medium" },
            { name: "Gabriel S.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Lucía A.", info: "Enfermedad: Jaqueca. Tratamiento: Paracetamol/Ibuprofeno. Actuación: 1 dosis de Apiretal (la niña lo lleva y sabe cuándo tomarlo).\nContacto: No especificado.", severity: "medium" },
            { name: "Lyanm S.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Sara B.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Sara G.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Sebastián", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Yeray G.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" }
        ],
        "5º Primaria": [
            { name: "Adriana P.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "África G.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Alba A.", info: "Enfermedad: Migrañas, alergia a picadura de avispa. Actuación: Paracetamol (lleva 1 pastilla), Pomada. Contacto: Francisco (657167007), Sara (660265011).", severity: "high" },
            { name: "Alberto S.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Alma C.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Dania G.", info: "Contacto: Araceli (614171476).", severity: "medium" },
            { name: "Daniel V.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Darío G.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Isabel L.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Javier S.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Jorge V.", info: "Enfermedad: Intolerancia al kiwi.\nContacto: No especificado.", severity: "medium" },
            { name: "Lola P.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Lucía H.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Oliver G.", info: "Enfermedad: Asma, alergia de contacto (piel). Tratamiento: Loratadina, Ventoduo. Actuación: Si hay tos, parar actividad física, dar Ventolín y agua. Contacto: Jonatan (618940992), Mª Cristina (673724999).", severity: "medium" },
            { name: "Sofía N.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Valentín B.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Vera H.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Xiomara T.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" }
        ],
        "6º Primaria": [
            { name: "Aimar A.", info: "Enfermedad: Alergia a frutos secos, frutas, pelo de animales, gramíneas, olivo. Tratamiento: Vacuna (1 mes). Síntomas: Picor/erupción (leve), problemas respiratorios (grave). Actuación: Llamar al centro de salud. Contacto: Madre (635344640).", severity: "high" },
            { name: "Alba N.", info: "Información: Operada de estenosis supravalvular aórtica. Indicación: Ejercicio físico normal.\nContacto: No especificado.", severity: "high" },
            { name: "Alejandro H.", info: "Enfermedad: Celiaquía. Síntomas: Diarrea. Contacto: Lorea (606660470).", severity: "medium" },
            { name: "Alma M.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Bruno G.", info: "Enfermedad: Alergia al polen.\nContacto: No especificado.", severity: "medium" },
            { name: "Daniel C.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Daniel P.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Delek H.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Elena F.", info: "Enfermedad: Alergia estacional. Tratamiento: Terbasmin, desloratadina.\nContacto: No especificado.", severity: "medium" },
            { name: "Irene C.", info: "Enfermedad: Trastorno por déficit de atención. Tratamiento: Medikinet 20 mg.\nContacto: No especificado.", severity: "medium" },
            { name: "Marcos C.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Marina A.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Mía R.", info: "Enfermedad: Talasemia. Tratamiento: Vitaminas. Síntomas: Falta de aire (sensación de ahogo). Actuación: Tranquilizar y reposar. Contacto: Félix (651138784), Madre (600019492).", severity: "high" },
            { name: "Nadia L.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Paola A.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Paula I.", info: "Enfermedad: Dermatitis atópica grave, Asma, Alergia a proteína de leche, huevo, frutos secos, polen y gramíneas. Tratamiento: Dupilumab 200mg. Síntomas: Urticaria. Actuación: Si hay contacto, administrar Estilsona 3ml y Atarax 5ml. Contacto: Elvira (661211335, 637834692).", severity: "high" },
            { name: "Puerto P.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Raúl G.", info: "Enfermedad: Asma. Tratamiento: Budesonida 160mg (1 inhalación/12h o a demanda). Síntomas: Falta de aire. Contacto: Carolina (608045291, 654149008).", severity: "medium" },
            { name: "Rocío Á.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Sara M.", info: "Enfermedad: TDAH. Tratamiento: Medikinet 10 mg.\nContacto: No especificado.", severity: "medium" },
            { name: "Thomas G.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Valeria S.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Víctor N.", info: "Información: Operado de estenosis supravalvular aórtica. Enfermedad: Alergia polen y gramíneas. Tratamiento: Ebastina 10mg, Aerosol. Indicación: Ejercicio físico normal. Contacto: Luis (609105931), Mª Teresa (625664796).", severity: "high" }
        ]
    },
    "ESO": {
        "1º ESO": [
            { name: "Daniella M.", info: "Enfermedad: Asma, Alergia.\nContacto: No especificado.", severity: "medium" },
            { name: "Guillermo M.", info: "Enfermedad: Alergia a gramíneas. Tratamiento habitual: Solo toma antihistamínicos en primavera.\nContacto: No especificado.", severity: "medium" },
            { name: "Leire C.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Lucas L.", info: "Enfermedad: Alergia al Polen, Rodilla (menisco). Tratamiento habitual: Antihistamínicos en primavera, Antiinflamatorios.\nContacto: No especificado.", severity: "medium" },
            { name: "Lucía R.", info: "Enfermedad: Alergia (Polen y gramíneas), Intolerancia (Gluten, Lácteos, Fructosa). Tratamiento habitual: Antiestamínicos. Actuación: Si es grave, inyectar urbasón. Contacto: Mª de Carmen (659075846), Bartolomé (619880433).", severity: "high" },
            { name: "Melany D.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Mirella G.", info: "Enfermedad: Alergia al pescado.\nContacto: No especificado.", severity: "high" },
            { name: "Natalia R.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Patrick F.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Raúl J.", info: "Enfermedad: Asma, Alergia a pólenes y gramíneas, hongo de la humedad, arbustos, malezas, pelo de gato, flor de olivo, fresno, laurel. Tratamiento habitual: Ventolín (según necesidad), Aerius (primavera), Budesonida. Síntomas: Dificultad respiratoria. Actuación: Administrar Ventolín según necesidad. Si no cede, inyectar Urbason (grave). Contacto: Mª Elisabeth (665894239).", severity: "high" },
            { name: "Ángelo M.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" }
        ],
        "2º ESO": [
            { name: "Adriana D.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Ainhoa P.", info: "Tratamiento habitual: Eutirox de 25.\nContacto: No especificado.", severity: "medium" },
            { name: "Ananda L.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Diego P.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Ender M.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Leyre S.", info: "Enfermedad: Alergia a familia del melocotón y derivados, Asma. Tratamiento habitual: A veces ventolín. Síntomas: Ronchas y enrojecimiento. Actuación: Polaramine. Contacto: Mónica (620034127).", severity: "medium" },
            { name: "Luis Miguel P.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Maicol H.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Mikel F.", info: "Enfermedad: Alergia a fruta (tomate, sandía, melón), Picaduras de mosquito, Polen, roble, arbustos, cenizo, Asma. Tratamiento habitual: Vacunas, antihistamínico, Singulair (1 diaria), Ebastel (1 diaria), Revinty (1 diaria). Síntomas: Tos, picor de garganta, sensación de falta de aire. Actuación: Leve (Tomar salbutamol de rescate), Grave (Medicación de rescate). Contacto: Mercedes (639328403).", severity: "medium" },
            { name: "Reina R.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Rodrigo P.", info: "Enfermedad: Afección de tiroides. Tratamiento habitual: Eutirox 50. Actuación: Sin indicaciones. Contacto: Kenia (651090443).", severity: "medium" },
            { name: "Román B.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Thalia T.", info: "Enfermedad: Problemas de riñón. Tratamiento habitual: Ditropan cada 12 horas.\nContacto: No especificado.", severity: "medium" },
            { name: "Víctor B.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Xiomara Y.", info: "Enfermedad: Hipotiroidismo. Tratamiento habitual: 1 pastilla diaria.\nContacto: No especificado.", severity: "medium" },
            { name: "Ángel M.", info: "Enfermedad: Alergia a gramíneas y olivo. Contacto: Fernando (662281734), Elizabeth (671985431).", severity: "medium" },
            { name: "Ángela M.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" }
        ],
        "3º ESO": [
            { name: "Alejandro C.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Amira E.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Carla A.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Claudia G.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "David G.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Enrique P.", info: "Enfermedad: Alergia al polen, humedad, gatos. Migrañas.\nContacto: No especificado.", severity: "medium" },
            { name: "Hugo L.", info: "Enfermedad: Alergia a Huevo, leche, fruta.\nContacto: No especificado.", severity: "high" },
            { name: "Javier C.", info: "Enfermedad: Alergia a Frutos secos, Alergia primaveral, Asma. Actuación: Ventolín. Contacto: Marisol (651181942), 659830666.", severity: "high" },
            { name: "Javier V.", info: "Enfermedad: TDA. Tratamiento habitual: Atenza 54mg.\nContacto: No especificado.", severity: "medium" },
            { name: "Jefferson G.", info: "Enfermedad: Alergia a Mosquitos, avispas, hormigas, Ácaros del polvo, polen.\nContacto: No especificado.", severity: "medium" },
            { name: "Lucía A.", info: "Enfermedad: Piel atópica.\nContacto: No especificado.", severity: "medium" },
            { name: "Lucía D.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Luz R.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Manuel M.", info: "Enfermedad: Trastorno del espectro autista grado I, TDAH combinado, tics motores simples y complejos. Tratamiento habitual: Elvanse 70.\nContacto: No especificado.", severity: "medium" },
            { name: "Pablo R.", info: "Enfermedad: Alergia al acebo.\nContacto: No especificado.", severity: "medium" },
            { name: "Paula R.", info: "Enfermedad: Bulto en rodilla izquierda. Actuación: En caso de sangrado, presionar y acudir al HOSPITAL.\nContacto: No especificado.", severity: "high" },
            { name: "Paula S.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Sofía J.", info: "Enfermedad: Miopía elevada. Tratamiento habitual: Atropina.\nContacto: No especificado.", severity: "medium" },
            { name: "Vera H.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Víctor S.", info: "Enfermedad: Diabetes (Hipoglucemias). Tratamiento habitual: Bomba de insulina. Síntomas: Leve (Sudores, temblores), Grave (Desmayo, pérdida de conocimiento). Actuación: Leve (Tomar hidratos de carbono), Grave (Administrar Glucagón).\nContacto: No especificado.", severity: "high" },
            { name: "Éric A.", info: "Enfermedad: Genu valgo, Alergia a polen, gramíneas, olivo, lolium perenne y ácaros. Síntomas: Tos, dificultad para respirar. Actuación: Tratamiento para rinoconjuntivitis y asma bronquial, Inhaladores. Contacto: Emiliano (607242511), Susana (617209649).", severity: "medium" }
        ],
        "4º ESO": [
            { name: "Antonela", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Carmen J.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Celia F.", info: "Enfermedad: Alergia a Polen, gramíneas, olivo, humedad.\nContacto: No especificado.", severity: "medium" },
            { name: "Jimena F.", info: "Enfermedad: Asma, Alergia a Piña, kiwi, melón, sandía, cerezas, mango, aguacate, ciruelas, tomate, Pólenes. Síntomas con ejercicio físico: Asfixia y mareo. Actuación: Aerosol (2 puffs) y urgencias. Contacto: Ana (692987095).", severity: "high" },
            { name: "Laura C.", info: "Enfermedad: Alergia al medicamento atropina.\nContacto: No especificado.", severity: "medium" },
            { name: "Leyre G.", info: "Enfermedad: Alergia estacional.\nContacto: No especificado.", severity: "medium" },
            { name: "Lucía A.", info: "Enfermedad: Alergia respiratoria. Tratamiento habitual: Cetirizina 10mg (1 al día), Ebastina 10mg (1 al día), Zaditen 0,25mg (3 al día).\nContacto: No especificado.", severity: "medium" },
            { name: "Melody P.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Miguel Ángel M.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Paula S.", info: "Enfermedad: Asma crónica, Alergia primaveral, Alergia a profilinas (tomate, sandía, melón...), pelo de gato, Picaduras de insectos (avispas y abejas). Tratamiento habitual: Cetirizina 1/24h de febrero a junio. Síntomas: Ingesta de profilinas (Picor/inflamación de garganta - leve), Asma en primavera (Silbidos en el pecho - grave). Actuación: Leve (Beber mucha agua), Grave (Ventolín/terbasmín a demanda). Contacto: Angélica (651755696).", severity: "medium" },
            { name: "Samuel I.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Sergio C.", info: "Sin patologías conocidas.\nContacto: No especificado.", severity: "low" },
            { name: "Ángel C.", info: "Enfermedad: Epilepsia (controlada), Alergia estacional.\nContacto: No especificado.", severity: "high" }
        ]
    }
};
